import { useState, memo, useCallback } from 'react';
import { GAME_CONFIG } from '../config';
import { supabase } from '../hooks/useGameState';
import { saveSession } from '../utils/sessionManager';
import CampfireAnimation from './CampfireAnimation';
import LobbyPlayerCard from './LobbyPlayerCard';

/**
 * Lobby component - Pre-game room with player list
 *
 * @param {Object} props
 * @param {Object} props.gameState - Current game state
 * @param {string} props.playerId - Current player's ID
 */
function Lobby({ gameState, playerId }) {
  const [playerName, setPlayerName] = useState('');

  // Check if current player has joined by looking in gameState.players
  const currentPlayer = gameState.players.find(p => p.id === playerId);
  const hasJoined = !!currentPlayer;

  // Derive host status from hostId in gameState
  const isHost = playerId === gameState.hostId;

  const handleJoinGame = useCallback(async (e) => {
    e.preventDefault();
    if (!playerName.trim()) return;

    try {
      // Direct database insert (validation happens via database trigger)
      // session_token is auto-generated by database DEFAULT
      const { error } = await supabase
        .from('game_players')
        .insert({
          room_code: gameState.roomCode,
          player_id: playerId,
          player_name: playerName.trim(),
          is_host: false
        });

      if (error) {
        throw error;
      }

      // Fetch the auto-generated session token
      const { data: playerData, error: fetchError } = await supabase
        .from('game_players')
        .select('session_token')
        .eq('room_code', gameState.roomCode)
        .eq('player_id', playerId)
        .single();

      if (!fetchError && playerData) {
        // Save session for reconnection
        const sessionData = {
          playerId: playerId,
          sessionToken: playerData.session_token,
          roomCode: gameState.roomCode,
          playerName: playerName.trim(),
          joinedAt: new Date().toISOString()
        };
        saveSession(sessionData);
      }

      setPlayerName('');
    } catch (error) {
      if (import.meta.env.DEV) {
        console.error('Failed to join room:', error);
      }
      alert(error.message || 'Failed to join room');
    }
  }, [playerName, gameState.roomCode, playerId]);

  const handleStartGame = useCallback(async () => {
    if (gameState.players.length < GAME_CONFIG.MIN_PLAYERS) {
      alert(`Need at least ${GAME_CONFIG.MIN_PLAYERS} players to start!`);
      return;
    }

    try {
      // Direct database update (validation + game state init via database triggers)
      const { error } = await supabase
        .from('game_rooms')
        .update({ status: 'playing' })
        .eq('room_code', gameState.roomCode)
        .eq('host_id', playerId); // Ensure only host can update

      if (error) {
        throw error;
      }

      // Game state will update automatically via Realtime
      if (import.meta.env.DEV) {
        console.log('Game started successfully');
      }
    } catch (error) {
      if (import.meta.env.DEV) {
        console.error('Failed to start game:', error);
      }
      alert(error.message || 'Failed to start game');
    }
  }, [gameState.players.length, gameState.roomCode, playerId]);

  const canStart = isHost && gameState.players.length >= GAME_CONFIG.MIN_PLAYERS;

  return (
    <div className="min-h-screen stars-bg flex items-center justify-center p-4">
      <div className="max-w-md w-full bg-amber-50 border-4 border-woodBrown rounded-lg p-8">
        {/* Campfire decoration */}
        <div className="flex justify-center mb-6">
          <CampfireAnimation />
        </div>

        {/* Room Code Display */}
        <div className="text-center mb-8">
          <h1 className="text-4xl font-pixel font-bold text-gray-800 mb-4 tracking-wide">SURFACE LEVEL</h1>
          <div className="bg-amber-100 border-4 border-amber-300 rounded-lg p-4">
            <p className="text-lg font-pixel text-gray-700 mb-1">ROOM CODE</p>
            <p className="text-6xl font-pixel text-warmAccent tracking-wider">{gameState.roomCode}</p>
          </div>
        </div>

        {/* Join Form or Player List */}
        {!hasJoined ? (
          <form onSubmit={handleJoinGame} className="mb-8">
            <label className="block text-xl font-pixel text-gray-700 mb-2">
              ENTER YOUR NAME
            </label>
            <input
              type="text"
              value={playerName}
              onChange={(e) => setPlayerName(e.target.value)}
              placeholder="Your name"
              maxLength={20}
              className="w-full px-4 py-3 border-4 border-gray-400 rounded-lg font-pixel text-xl focus:border-warmAccent outline-none bg-white"
              autoFocus
            />
            <button
              type="submit"
              className="w-full mt-4 bg-warmAccent text-white border-4 border-woodBrown py-3 rounded-lg font-pixel text-2xl hover:bg-orange-600 active:translate-y-1"
            >
              JOIN GAME
            </button>
          </form>
        ) : (
          <div className="mb-8">
            {/* Player List */}
            <h2 className="text-2xl font-pixel text-gray-800 mb-4">
              PLAYERS ({gameState.players.length}/{GAME_CONFIG.MAX_PLAYERS})
            </h2>
            <div className="space-y-2">
              {gameState.players.map((player) => (
                <LobbyPlayerCard
                  key={player.id}
                  player={player}
                  isHost={player.id === gameState.hostId}
                />
              ))}
            </div>

            {/* Questions Per Level Indicator */}
            <div className="mt-4 bg-amber-100 border-4 border-amber-300 rounded-lg p-3">
              <p className="text-lg font-pixel text-gray-800 text-center leading-relaxed">
                GAME FORMAT: EACH PLAYER ANSWERS 1 QUESTION PER LEVEL
                <br />
                <span className="text-warmAccent">
                  ({gameState.players.length} {gameState.players.length === 1 ? 'PLAYER' : 'PLAYERS'} = {gameState.players.length} QUESTIONS PER LEVEL)
                </span>
              </p>
            </div>

            {/* Start Game Button (Host Only) */}
            {isHost && (
              <button
                onClick={handleStartGame}
                disabled={!canStart}
                className={`w-full mt-6 py-4 rounded-lg font-pixel text-2xl border-4 ${
                  canStart
                    ? 'bg-level3 text-white border-green-800 hover:bg-yellow-500 active:translate-y-1'
                    : 'bg-gray-300 text-gray-500 border-gray-400 cursor-not-allowed'
                }`}
              >
                {canStart
                  ? 'START GAME'
                  : `NEED ${GAME_CONFIG.MIN_PLAYERS - gameState.players.length} MORE PLAYER(S)`}
              </button>
            )}

            {/* Waiting Message (Non-Host) */}
            {!isHost && (
              <p className="text-center text-gray-700 mt-6 text-xl font-pixel">
                WAITING FOR HOST TO START THE GAME...
              </p>
            )}
          </div>
        )}

        {/* Game Info */}
        <div className="bg-amber-100 border-4 border-amber-300 rounded-lg p-4 font-pixel text-gray-800">
          <p className="text-xl mb-3">HOW TO PLAY:</p>
          <ul className="space-y-2 text-lg leading-relaxed">
            <li>- START WITH THE MOST INTIMATE QUESTIONS (LEVEL 5)</li>
            <li>- TAKE TURNS ANSWERING QUESTIONS</li>
            <li>- WORK YOUR WAY DOWN TO SMALL TALK (LEVEL 1)</li>
            <li>- BE HONEST, BE VULNERABLE, HAVE FUN!</li>
          </ul>
        </div>
      </div>
    </div>
  );
}

export default memo(Lobby);
